function [ V ] = getVelocity( X, V, P, S, GB, I, params, dir, DIM)
    
    V = params.IW * V + dir * ( ...
        I         * params.CC * rand * (P - X) + ...
        I         * params.SC * rand * (GB.X - X) + ...
        (I - 1)   * params.GC * rand * S);
    
end
